"""
End-of-Well Report Swarm
Generates a comprehensive end-of-well report from all available data sources.
"""
from __future__ import annotations
import logging
from pathlib import Path
from typing import Any

from ..orchestrator import OrchestratorAgent, SwarmContext, SwarmResult

logger = logging.getLogger(__name__)

class EndOfWellSwarm:
    """
    Comprehensive end-of-well report generator.
    """
    def __init__(
        self,
        well_name: str | None = None,
        api: str | None = None,
        operator: str | None = None,
        field_name: str | None = None,
        pad: str | None = None,
        lateral_length_ft: float | None = None,
        lateral_length_m: float | None = None,
        total_manhours: float | None = None,
        verbose: bool = True,
    ) -> None:
        self.orchestrator = OrchestratorAgent(verbose=verbose)
        self._context_kwargs = {
            k: v for k, v in dict(
                well_name=well_name, api=api, operator=operator,
                field_name=field_name, pad=pad,
                lateral_length_ft=lateral_length_ft,
                lateral_length_m=lateral_length_m,
                total_manhours=total_manhours,
            ).items() if v is not None
        }

    async def run(self, file_paths: list[str | Path]) -> SwarmResult:
        logger.info(f"Starting End-of-Well Swarm for well: {self._context_kwargs.get('well_name', 'Unknown')}")
        ctx = SwarmContext(**self._context_kwargs)
        result = await self.orchestrator.run(file_paths, ctx)
        
        eow_appendix = _build_eow_appendix(result)
        result.unified_report = result.unified_report + "\n\n" + eow_appendix
        logger.info("End-of-Well Swarm completed")
        return result

def _build_eow_appendix(result: SwarmResult) -> str:
    """Append end-of-well specific sections."""
    lines = [
        "END-OF-WELL SUMMARY",
        "=" * 60,
    ]
    
    flags = result.quality_flags + result.cross_domain_flags
    if flags:
        lines.append("\nLESSONS LEARNED / OBSERVATIONS")
        lines.append("-" * 40)
        seen: set[str] = set()
        for flag in flags:
            prefix = flag.split(":")[0].strip("[]").upper() if ":" in flag else "GENERAL"
            if prefix not in seen:
                seen.add(prefix)
                matching = [f for f in flags if f.startswith(f"[{prefix.lower()}]") or f.upper().startswith(prefix)]
                if matching:
                    lines.append(f"  {prefix}: {matching[0][:120]}")
                    
    lines.append("\nREPORT GENERATED BY OIL & GAS AGENT SWARM")
    lines.append(f"Task ID: {result.task_id}")
    lines.append(f"Files analyzed: {result.files_processed}")
    lines.append(f"Agents run: {result.agents_succeeded} succeeded, {result.agents_failed} failed")
    lines.append(f"Analysis time: {result.elapsed_seconds}s")
    return "\n".join(lines)